// import './globals.css'
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ReactQueryProvider } from './ReactQueryProvider';
import StyledComponentsRegistry from './registry';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ReactQueryProvider>
      <html lang="en">
      <StyledComponentsRegistry>
        <body>{children}</body>
      </StyledComponentsRegistry>
      </html>
    </ReactQueryProvider>
  );
}
